oai:
  docker:
    network:
      data_iface: data
      name: public_net
      subnet: "172.20.0.0/16"
      bridge:
        name: rfsim5g-public
        
core:
  upf:
    ip_prefix: "192.168.252.0/24"
    iface: "access"
  amf:
    ip: "172.16.248.6"
